---

- name: Import secrets
  ansible.builtin.include_vars:
    file: "{{ secrets_file_path }}"

- name: Print secrets file path
  ansible.builtin.debug:
    msg: 
    - "secrets_file_path         : {{ secrets_file_path }}"

- name: Overwrite variables from secrets
  ansible.builtin.set_fact:
    # Overwrite server variables
    pve_node :          "{{  vars[ host_vars  ~ '_pve_node'] }}"
    pve_api_host :      "{{ hostvars[ vars[ host_vars  ~ '_pve_node']]['ansible_host'] }}"
    pve_api_user :      "{{ vars[ host_vars  ~ '_pve_api_user'] }}"
    pve_api_password :  "{{ vars[ host_vars  ~ '_pve_api_password'] }}"
    # Overwrite LXC variables
    pve_lxc_root_password :           "{{ vars[ host_vars  ~ '_pve_lxc_root_password'] }}"
    pve_lxc_root_authorized_pubkey :  "{{ lookup('file', vars[ host_vars ~ '_pve_lxc_root_authorized_pubkey']) }}"
    
    # Overwrite user to be added variables
    admin_name :        "{{ vars[ host_vars ~ '_admin_user'] }}"
    admin_password :    "{{ vars[ host_vars ~ '_admin_password'] }}"

- name: Print gathering facts
  ansible.builtin.debug:
    msg: 
    - "pve_node         : {{ pve_node }}"
    - "pve_api_host     : {{ pve_api_host }}"
    - "pve_api_user     : {{ pve_api_user }}"
    - "pve_api_password : {{ pve_api_password }}"
  when: debug_mode | default(false)

- name: Node variables file
  ansible.builtin.debug:
    msg: "{{ ansible_host_vars_dir }}/{{ host_name }}.yml"
  when: debug_mode

- name: Import node variables
  ansible.builtin.include_vars:
    file: "{{ ansible_host_vars_dir }}/{{ host_name }}.yml"

- name: Print node variables
  ansible.builtin.debug:
    msg: 
    - "pve_node                 : {{ pve_node }}"
    - "pve_api_host             : {{ pve_api_host }}"
    - "pve_api_user             : {{ pve_api_user }}"
    - "pve_api_password         : {{ pve_api_password }}"
    - " ---------------------------------------- "
    - " ---------------------------------------- "
    - "pve_lxc_root_password    : {{ pve_lxc_root_password }}"
    - "pve_lxc_root_authorized_pubkey : {{ pve_lxc_root_authorized_pubkey }}"
    - " ---------------------------------------- "
    - " ---------------------------------------- "
    - "admin_name               : {{ admin_name }}"
    - "admin_password           : {{ admin_password }}"
    - " ---------------------------------------- "
    - " ---------------------------------------- "
    - "pve_lxc_name             : {{ pve_lxc_name | default(omit) }}"
    - "pve_lxc_vmid             : {{ pve_lxc_vmid | default(omit) }}"
    - "pve_lxc_ostemplate_name  : {{ pve_lxc_ostemplate_name | default(omit) }}"
    - "pve_lxc_ip_address       : {{ pve_lxc_ip_address | default(omit) }}"
    - "pve_lxc_ip_mask          : {{ pve_lxc_ip_mask | default(omit) }}"
    - "pve_lxc_ip_gateway       : {{ pve_lxc_ip_gateway | default(omit) }}"
    - "pve_lxc_nameserver       : {{ pve_lxc_nameserver | default(omit) }}"
    - "pve_lxc_searchdomain     : {{ pve_lxc_searchdomain | default(omit) }}"
    - "pve_lxc_description      : {{ pve_lxc_description | default(omit) }}"
  when: debug_mode | default(false)