---
# EN: Render the main Unbound configuration / RU: Генерация основного конфига Unbound

- name: "Deploy Unbound server config"
  ansible.builtin.template:
    src: 10-server.conf.j2
    dest: "{{ unbound_config_path }}"
    owner: root
    group: root
    mode: "0644"
    validate: "unbound-checkconf %s"
  notify: unbound_restart
