---

- name: Installing python3 and python3-pip on the Proxmox node
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip
    - python3-proxmoxer

- name: Get VM information
  community.general.proxmox_vm_info:
    api_host: "{{ pve_api_host }}"
    node: "{{ pve_node }}"
    api_user: "{{ pve_api_user | default(omit) }}"
    api_password: "{{ pve_api_password | default(omit) }}"
    vmid: "{{ pve_lxc_vmid | default(omit) }}"
  register: pve_vms_info

- name: Get VM_ID info
  set_fact:
    pve_vmid_info: "{{ pve_vms_info.proxmox_vms | default([]) | map(attribute='vmid') | default([]) | join(',') }}"

- debug:
    msg: "pve_vmid_info:  {{ pve_vmid_info }} "

- name: Check VM exists
  set_fact:
    pve_lxc_state: present
  #debug:
  #  msg: "pve_lxc_state ========================"
  when: pve_vmid_info|length == 0 #(bar is not defined) or (bar|length == 0)

- name: Check VM started
  set_fact:
    pve_lxc_state: started
  #debug:
  #  msg: "pve_lxc_state  >>>>>>>>>>>>>>>>>>>>>"
  when: pve_vmid_info|length > 0

#- debug:
#    msg: "pve_lxc_state IS {{ pve_lxc_state }}"

- name: Check OS template exists
  stat:
    path: "{{ pve_lxc_ostemplate_src }}"
  register: pve_lxc_ostemplate_exists

- name: Download the container template if it's needed
  ansible.builtin.get_url:
    url: "{{ pve_lxc_ostemplate_url }}"
    dest: "{{ pve_lxc_ostemplate_src_dest }}"
  register: pve_lxc_ostemplate_downloaded
  when: not pve_lxc_ostemplate_exists.stat.exists


- name: Add LXC container template to node
  community.general.proxmox_template:
    node: "{{ pve_node }}"
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user | default(omit) }}"
    api_password: "{{ pve_api_password | default(omit) }}"
    api_token_id: "{{ pve_api_token_id | default(omit) }}"
    api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
    template: "{{ pve_lxc_ostemplate_name | default(omit) }}"
    src: "{{ pve_lxc_ostemplate_src if(pve_lxc_ostemplate_src is defined) else ( pve_lxc_ostemplate_downloaded.dest if(pve_lxc_ostemplate_downloaded.dest is defined) ) | default(omit) }}"
    storage: "{{ pve_lxc_ostemplate_storage | default(omit) }}"
    content_type: "{{ pve_lxc_ostemplate_content_type | default(omit) }}"
    timeout: "{{ pve_lxc_ostemplate_timeout | default(omit) }}"
    force: "{{ pve_lxc_ostemplate_force | default(omit) }}"
    validate_certs: "{{ pve_validate_certs | default(omit) }}"
    state: "{{ pve_lxc_ostemplate_state  | default(omit) }}"


- name: DEBUG OUTPUT
  ansible.builtin.debug:
    msg:
    - "pve_default_behavior = {{ pve_default_behavior }}"
    - "nameserver = {{ pve_lxc_nameserver }}"
    - "searchdomain = {{ pve_lxc_searchdomain }}"
    - "--------------------------------"
    - "vmid = {{ pve_lxc_vmid }}"
    - "hostname = {{ pve_hostname }}"
  when: debug_mode



- name: Create the container
  community.general.proxmox:
    vmid: "{{ pve_lxc_vmid | default(omit) }}"
    node: "{{ pve_node }}"
    api_user: "{{ pve_api_user | default(omit) }}"
    api_password: "{{ pve_api_password | default(omit) }}"

    api_token_id: "{{ pve_api_token_id | default(omit) }}"
    api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
    pubkey: "{{ pve_lxc_root_authorized_pubkey | default(omit) }}"

    api_host: "{{ pve_api_host }}"
    password: "{{ pve_lxc_root_password }}"
    
    #storage: "{{ pve_lxc_storage | default(omit) }}"
    hostname: "{{ pve_hostname }}"
    description: "{{ pve_lxc_description }}" #description: "{{ pve_lxc_description | default(omit) }}"
    ostemplate: "{{ pve_lxc_ostemplate_storage | default('local') }}:{{ pve_lxc_ostemplate_content_type | default('vztmpl') }}/{{ pve_lxc_ostemplate_name if(pve_lxc_ostemplate_name is defined) else ( pve_lxc_ostemplate_url | urlsplit('path') | basename ) }}"

    validate_certs: "{{ pve_validate_certs | default(omit) }}"
    hookscript: "{{ pve_lxc_hookscript | default(omit) }}"
    
    cores:    "{{ pve_lxc_cpu_cores | default(omit) }}"
    cpus:     "{{ pve_lxc_cpu_limit | default(omit) }}"
    cpuunits: "{{ pve_lxc_cpu_units | default(omit) }}"
    memory:   "{{ pve_lxc_memory    | default(omit) }}"
    swap:     "{{ pve_lxc_swap      | default(omit) }}"
    disk:     "{{ pve_lxc_storage | default(omit) }}:{{ pve_lxc_disk      | default(omit) }}"

    #disk_volume:
    #  storage: "{{ pve_lxc_storage | default(omit) }}"
    #  size:    "{{ pve_lxc_disk      | default(omit) }}"


    onboot:       "{{ pve_onboot            | default(omit) }}"
    unprivileged: "{{ pve_lxc_unprivileged  | default(omit) }}"

    #ip_address:   "{{ pve_lxc_ip_address    | default(omit) }}"   #Don't work
    nameserver:   "{{ pve_lxc_nameserver    | default(omit) }}"
    searchdomain: "{{ pve_lxc_searchdomain  | default(omit) }}"

    mounts: >-
      {   {%- for item in pve_lxc_mounts -%}
            "{{ item.id }}":"{{ item.storage|default('local-lvm') }}:{{ item.size|default(32) }},mp={{ item.mount_point|default('/mnt/mp0') }},{% if item.acl is defined %}{% if (item.acl) %}acl=1{% else %}acl=0{% endif %},{% endif %}{% if item.quota is defined and item.quota %}quota=1,{% endif %}{% if item.read_only is defined and item.read_only %}ro=1,{% endif %}{% if item.backup is defined and item.backup %}backup=1,{% endif %}{% if item.skip_replication is defined and item.skip_replication %}replicate=0{% endif %}",
          {%- endfor -%}  }
    netif: >-
      {   {%- for item in pve_lxc_net_interfaces -%}
            "{{ item.id }}":"name={{ item.name }},bridge={{ item.bridge }},{% if (item.hwaddr is defined) %}hwaddr={{ item.hwaddr }},{% endif %}{% if (item.ip4 is defined) %}ip={{ item.ip4 }}{% endif %}{% if (item.netmask4 is defined) %}/{{ item.netmask4 }},{% else %},{% endif %}{% if (item.gw4 is defined) %}gw={{ item.gw4 }},{% endif %}{% if (item.ip6 is defined) %}ip6={{ item.ip6 }}{% endif %}{% if (item.netmask6 is defined) %}/{{ item.netmask6 }},{% else %},{% endif %}{% if (item.gw6 is defined) %}gw6={{ item.gw6 }},{% endif %}{% if (item.firewall is defined and item.firewall) %}firewall=1,{% endif %}{% if (item.rate_limit is defined) %}rate={{ item.rate_limit }},{% else %},{% endif %}{% if (item.vlan_tag is defined) %}tag={{ item.vlan_tag }}{% endif %}",
          {%- endfor -%} 
      }
    
    features: "{{ pve_lxc_features  | default(omit) }}"
    timeout:  "{{ pve_lxc_timeout   | default(omit) }}"
    force:    "{{ pve_lxc_force     | default(true) }}"
    state:    "{{ pve_lxc_state }}"

  register: pve_lxc_container_created

- name: Extract the container VMID
  ansible.builtin.shell: |
    set -o pipefail
    pvesh get nodes/{{ pve_node }}/lxc --output-format=json 2>/dev/null | sed 's/},{/}\n{/g' | grep -w "{{ pve_hostname }}" | grep -Po '("vmid":")\K[[:digit:]]+(?=")'
  args:
    executable: /bin/bash
  changed_when: false
  delegate_to: "{{ pve_api_host }}"
  register: pve_lxc_extracted_vmid
  when:
    - pve_lxc_vmid is not defined
    - pve_lxc_container_created is succeeded

- name: Set variable with the corresponding VMID for the container in case it has not been defined
  ansible.builtin.set_fact:
    pve_lxc_inferred_vmid: "{{ pve_lxc_vmid if (pve_lxc_vmid is defined) else pve_lxc_extracted_vmid.stdout }}"

- block:
  - name: Additional configurations directly on the container .conf file
    ansible.builtin.lineinfile:
      unsafe_writes: yes # Otherwise Proxmox denies permission
      path: "{{ proxmox_config_dir | default('/etc/pve') }}/nodes/{{ pve_node }}/lxc/{{ pve_lxc_inferred_vmid }}.conf"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: "{{ item.state | default(omit) }}"
    with_items: "{{ pve_lxc_additional_configurations }}"
    register: pve_lxc_additional_configurations_result

  - name: Reboot (turn off and then turn on) the container if the configuration file was modified
    community.general.proxmox:
      node: "{{ pve_node }}"
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user | default(omit) }}"
      api_password: "{{ pve_api_password | default(omit) }}"
      api_token_id: "{{ pve_api_token_id | default(omit) }}"
      api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
      vmid: "{{ pve_lxc_inferred_vmid }}"
      state: stopped
    when: pve_lxc_additional_configurations_result is changed
  when: pve_lxc_additional_configurations is defined

- name: pve_lxc_container_created status
  ansible.builtin.debug:
    msg: "pve_lxc_container_created status: {{ pve_lxc_container_created }}"
  when: debug_mode


- name: Ensure the container is turned on
  community.general.proxmox:
    node: "{{ pve_node }}"
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user | default(omit) }}"
    api_password: "{{ pve_api_password | default(omit) }}"
    api_token_id: "{{ pve_api_token_id | default(omit) }}"
    api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
    vmid: "{{ pve_lxc_inferred_vmid }}"
    state: started
  notify: pve_lxc wait for connection
  when: (pve_lxc_container_created is not defined) or (pve_lxc_container_created is succeeded)

...
