---
galaxy_info:
  author: System Administrator
  description: Debian package installation role supporting Debian OS family with comprehensive validation, advanced debugging capabilities, and production-ready error handling. Supports Ubuntu and Debian distributions.
  company: Infrastructure Team
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    # Debian family distributions (ansible_os_family: Debian)
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - system
    - packages
    - apt
    - ubuntu
    - debian
    - validation
    - debugging
    - debian-platform
dependencies: []
