---
# =============================================================================
# System Locale Configuration Role - Handlers
# =============================================================================
# This file contains handlers for locale configuration changes
# Файл содержит обработчики для изменений конфигурации локализации
# =============================================================================

# Debian locale reload handler / Обработчик перезагрузки локализации для Debian
- name: reload locale
  ansible.builtin.command: "{{ locale_reload_command }}"
  register: locale_reload_result
  changed_when: locale_reload_result.rc == 0
  failed_when: false
  listen: reload locale
  throttle: 1  # Reload one host at a time / Перезагружать по одному хосту
  tags:
    - handlers
    - locale

# Display locale reload results (English) / Отображение результатов перезагрузки локализации
- name: "Display locale reload results"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "Locale Configuration Reload Results:"
      - "============================================================================="
      - "OS Family:             {{ ansible_os_family }}"
      - "Command:               {{ locale_reload_command }}"
      - "Return Code:           {{ locale_reload_result.rc | default('N/A') }}"
      - "Changed:               {{ locale_reload_result.changed | default(false) }}"
      - "Output:                {{ locale_reload_result.stdout | default('N/A') }}"
      - "Errors:                {{ locale_reload_result.stderr | default('N/A') }}"
      - "============================================================================="
  when:
    - debug_mode | default(false)
  listen: reload locale
  tags:
    - debug
    - handlers

# Debian console reload handler / Обработчик перезагрузки консоли для Debian
- name: reload console
  ansible.builtin.command: "{{ console_reload_command }}"
  register: console_reload_result
  failed_when: false
  changed_when: console_reload_result.rc == 0
  listen: reload console
  tags:
    - handlers
    - console

# Display console reload results (English) / Отображение результатов перезагрузки консоли
- name: "Display console reload results (English)"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "Console Configuration Reload Results:"
      - "============================================================================="
      - "OS Family:             {{ ansible_os_family }}"
      - "Command:               {{ console_reload_command }}"
      - "Return Code:           {{ console_reload_result.rc | default('N/A') }}"
      - "Changed:               {{ console_reload_result.changed | default(false) }}"
      - "Output:                {{ console_reload_result.stdout | default('N/A') }}"
      - "Errors:                {{ console_reload_result.stderr | default('N/A') }}"
      - "============================================================================="
  when:
    - debug_mode | default(false)
  listen: reload console
  tags:
    - debug
    - handlers

# Reload timezone configuration / Перезагрузка конфигурации часового пояса
- name: reload timezone handler
  ansible.builtin.command: "timedatectl set-timezone {{ timezone }}"
  register: timezone_reload_result
  changed_when: timezone_reload_result.rc == 0
  failed_when: false
  listen: reload timezone
  tags:
    - handlers
    - timezone

# Display timezone reload results (English) / Отображение результатов перезагрузки часового пояса
- name: "Display timezone reload results (English)"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "Timezone Configuration Reload Results:"
      - "============================================================================="
      - "Command:               timedatectl set-timezone {{ timezone }}"
      - "Return Code:           {{ timezone_reload_result.rc | default('N/A') }}"
      - "Changed:               {{ timezone_reload_result.changed | default(false) }}"
      - "Output:                {{ timezone_reload_result.stdout | default('N/A') }}"
      - "Errors:                {{ timezone_reload_result.stderr | default('N/A') }}"
      - "============================================================================="
  when:
    - debug_mode | default(false)
  listen: reload timezone
  tags:
    - debug
    - handlers

