---
# =============================================================================
# Package Installation Role Handlers
# =============================================================================
# This file contains handlers for the package installation role
# for restarting services and performing post-installation tasks.
#
# Этот файл содержит обработчики для роли установки пакетов
# для перезапуска сервисов и выполнения пост-установочных задач.
# =============================================================================

# Gather information about services on the system
# Сбор информации о сервисах в системе
- name: "Gather service facts"
  ansible.builtin.service_facts:

# Restart services that may have been affected by package installation
# Перезапуск сервисов, которые могли быть затронуты установкой пакетов
- name: "Restart system services after package installation"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - ssh
  when: 
    - ansible_facts['services'][item] is defined
    - ansible_facts['services'][item]['status'] | default('not-found') != 'not-found'
  ignore_errors: yes
  tags:
    - handlers
    - services
    - restart  
    
  # Reload system configuration that may have been updated by package installation
  # Перезагрузка системной конфигурации, которая могла быть обновлена установкой пакетов
- name: "Reload system configuration after package installation"
  ansible.builtin.command: systemctl daemon-reload
  register: daemon_reload_result
  changed_when: daemon_reload_result.rc == 0
  failed_when: daemon_reload_result.rc != 0
  tags:
    - handlers
    - systemd
    - reload
