---
# NetBox Compose deployment configuration
# Конфигурация Compose-развертывания NetBox

# Boolean. Enable change notifications in debug output.
# Логическое значение. Включает уведомления об изменениях в debug-выводе.
netbox_docker_local_debug_mode: false

# String. Docker Compose project directory.
# Строка. Каталог проекта Docker Compose.
netbox_docker_local_project_directory: "/opt/netbox"
