---
# Preflight checks before role execution
# Предварительные проверки перед выполнением роли

- name: Check Ansible version
  ansible.builtin.assert:
    that:
      - ansible_version.full is version('2.14', '>=')
    fail_msg: |
      EN: This role requires Ansible 2.14 or higher. Current version: {{ ansible_version.full }}
      RU: Эта роль требует Ansible 2.14 или выше. Текущая версия: {{ ansible_version.full }}
    success_msg: |
      EN: Ansible version check passed: {{ ansible_version.full }}
      RU: Проверка версии Ansible пройдена: {{ ansible_version.full }}
  tags: ['preflight']

- name: Check OS compatibility
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat', 'Suse']
      - ansible_distribution_version is version(min_os_version[ansible_os_family], '>=')
    fail_msg: |
      EN: Unsupported OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
      RU: Неподдерживаемая ОС: {{ ansible_distribution }} {{ ansible_distribution_version }}
    success_msg: |
      EN: OS compatibility check passed: {{ ansible_distribution }} {{ ansible_distribution_version }}
      RU: Проверка совместимости ОС пройдена: {{ ansible_distribution }} {{ ansible_distribution_version }}
  vars:
    min_os_version:
      Debian: "11"
      RedHat: "8"
      Suse: "15"
  tags: ['preflight']

- name: Check required Python modules
  ansible.builtin.assert:
    that:
      - ansible_python_version is version('3.8', '>=')
    fail_msg: |
      EN: Python 3.8+ is required. Current version: {{ ansible_python_version }}
      RU: Требуется Python 3.8+. Текущая версия: {{ ansible_python_version }}
    success_msg: |
      EN: Python version check passed: {{ ansible_python_version }}
      RU: Проверка версии Python пройдена: {{ ansible_python_version }}
  tags: ['preflight']

- name: Display preflight check results
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "Preflight Checks Summary:"
      - "============================================================================="
      - "Ansible Version:          {{ ansible_version.full }}"
      - "Python Version:           {{ ansible_python_version }}"
      - "Operating System:         {{ ansible_distribution }} {{ ansible_distribution_version }}"
      - "OS Family:                {{ ansible_os_family }}"
      - "System Architecture:      {{ ansible_architecture }}"
      - "Hostname:                 {{ ansible_hostname }}"
      - "All Checks:               PASSED"
      - "============================================================================="
  when: debug_mode | default(false)
  tags: ['preflight', 'debug']

