---
# EN: RedHat/CentOS/RHEL specific tasks
# RU: Задачи для RedHat/CentOS/RHEL

# EN: Install required packages for RedHat/CentOS/RHEL
# RU: Установка необходимых пакетов для RedHat/CentOS/RHEL
- name: Install required packages (RedHat/CentOS/RHEL)
  ansible.builtin.dnf:
    name: "{{ required_packages }}"
    state: present
  when: ansible_distribution_major_version | int >= 8
  retries: "{{ retries | default(3) }}"
  delay: "{{ retry_delay | default(5) }}"
  register: package_installation_result_dnf
  tags:
    - packages
    - install

- name: Install required packages (RedHat/CentOS/RHEL) - yum
  ansible.builtin.yum:
    name: "{{ required_packages }}"
    state: present
  when: ansible_distribution_major_version | int < 8
  retries: "{{ retries | default(3) }}"
  delay: "{{ retry_delay | default(5) }}"
  register: package_installation_result_yum
  tags:
    - packages
    - install

# EN: Set package installation result
# RU: Установка результата установки пакетов
- name: Set package installation result
  ansible.builtin.set_fact:
    package_installation_result: "{{ package_installation_result_dnf if ansible_distribution_major_version | int >= 8 else package_installation_result_yum }}"
  tags:
    - packages
    - facts

# EN: Log package installation (RedHat/CentOS/RHEL)
# RU: Логирование установки пакетов (RedHat/CentOS/RHEL)
- name: Log package installation (RedHat/CentOS/RHEL)
  ansible.builtin.lineinfile:
    path: "{{ log_file | default('/var/log/ansible-changes.log') }}"
    line: '{{ {
      "timestamp": ansible_date_time.iso8601,
      "level": "INFO",
      "event_type": "PACKAGE_INSTALL",
      "package_list": required_packages,
      "package_manager": ansible_distribution_major_version | int >= 8 | ternary("dnf", "yum"),
      "user": ansible_user_id,
      "host": inventory_hostname,
      "playbook": ansible_play_name,
      "correlation_id": ansible_date_time.epoch,
      "message": "Required packages installed",
      "metadata": {
        "os_family": ansible_os_family,
        "os_distribution": ansible_distribution,
        "os_version": ansible_distribution_version,
        "packages_installed": package_installation_result.changed | default(false),
        "packages_count": required_packages | length
      }
    } | to_json }}'
    create: true
    mode: '0644'
  when: log_file is defined
  tags:
    - packages
    - logging
