---
# =============================================================================
# System Locale Configuration Role - Main Tasks
# =============================================================================
# This role configures system locale, timezone, keyboard layout and console font
# for Debian/Ubuntu systems.
#
# Роль настройки системной локализации, часового пояса, раскладки клавиатуры
# и консольного шрифта для систем Debian/Ubuntu.
# =============================================================================

# Gather system facts
#Сбор системной информации
- name: "Gather system facts"
  ansible.builtin.setup:
    gather_subset:
      - all
  tags:
    - facts
    - always

# Preflight checks before role execution
#Предварительные проверки перед выполнением роли
- name: "Preflight checks before role execution"
  ansible.builtin.include_tasks: preflight.yml
  tags:
    - preflight
    - always

# Validate input parameters before configuration
# Валидация входных параметров перед конфигурацией
- name: "Validate locale configuration parameters"
  ansible.builtin.include_tasks: validate.yml
  when: validate_parameters | bool
  register: validation_result
  tags:
    - validation
    - locale
    - parameters

# Display comprehensive system information for debugging (English)
# Отображение полной системной информации для отладки
- name: "Display comprehensive system information for locale configuration (English)"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "System Information for Locale Configuration:"
      - "============================================================================="
      - "Distribution:          {{ ansible_distribution }}"
      - "Version:               {{ ansible_distribution_version }}"
      - "Architecture:          {{ ansible_architecture }}"
      - "Kernel:                {{ ansible_kernel }}"
      - "Hostname:              {{ ansible_hostname }}"
      - "FQDN:                  {{ ansible_fqdn }}"
      - "Primary Locale:        {{ locale_primary }}"
      - "Timezone:              {{ timezone }}"
      - "Keyboard Layout:       {{ keyboard_layout }}"
      - "Console Font:          {{ console_font }}"
      - "Backup Enabled:        {{ backup_enabled }}"
      - "Validation Enabled:    {{ validate_parameters }}"
      - "Debug Mode:            {{ debug_mode }}"
      - "Strict Validation:     {{ strict_validation }}"
      - "============================================================================="
  when: debug_mode | default(false)
  register: system_info_display
  tags:
    - debug
    - locale
    - system
    - information

# Create backup copies of existing locale configuration files
# Создание резервных копий существующих файлов конфигурации локализации
- name: "Create backup copies of existing locale configuration files"
  block:
    - name: "Backup locale configuration files"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ item }}{{ backup_suffix }}"
        remote_src: true
        backup: no
        mode: '0644'
      loop:
        - /etc/default/locale
        - /etc/environment
        - /etc/locale.gen
        - /etc/default/console-setup
      register: backup_result
      tags:
        - backup
        - locale
        - files
        - safety
  rescue:
    - name: "Backup operation failed - continuing without backup"
      ansible.builtin.debug:
        msg: "Warning: Could not create backup copies. Continuing with configuration."
      register: backup_result
      failed_when: false
  when: backup_enabled | bool
  tags:
    - backup
    - locale
    - files
    - safety

# Display detailed backup operation results (English)
# Отображение детальных результатов операции резервного копирования
- name: "Display detailed backup operation results (English)"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "Backup Operation Results:"
      - "============================================================================="
      - "Source File:            {{ item.src }}"
      - "Backup File:            {{ item.dest }}"
      - "Operation Status:       {{ 'SUCCESS' if item.changed else 'SKIPPED' }}"
      - "File Exists:            {{ 'YES' if item.src is file else 'NO' }}"
      - "Backup Created:         {{ 'YES' if item.changed else 'NO' }}"
      - "============================================================================="
  loop: "{{ backup_result.results | default([]) }}"
  when: 
    - debug_mode | default(false)
    - backup_enabled | default(true)
    - backup_result is defined
  tags:
    - debug
    - backup
    - results



# Generate primary locale
# Генерация основной локали
- name: "Generate primary locale"
  block:
    - name: "Generate primary locale"
      community.general.locale_gen:
        name: "{{ locale_primary }}"
        state: present
      register: primary_locale_gen_result
  rescue:
    - name: "Log primary locale generation failure (structured JSON)"
      # Log primary locale generation failure
      # Логирование ошибки генерации основной локали
      ansible.builtin.lineinfile:
        path: "{{ log_file | default('/var/log/ansible-changes.log') }}"
        line: '{{ {
          "timestamp": ansible_date_time.iso8601,
          "level": "ERROR",
          "event_type": "PRIMARY_LOCALE_GEN_FAILED",
          "locale_primary": locale_primary,
          "user": ansible_user_id,
          "host": inventory_hostname,
          "playbook": ansible_play_name,
          "correlation_id": ansible_date_time.epoch,
          "message": "Primary locale generation failed",
          "metadata": {
            "rollback_enabled": enable_rollback | default(true),
            "os_family": ansible_os_family,
            "os_version": ansible_distribution_version,
            "error_type": "PRIMARY_LOCALE_GENERATION_ERROR"
          }
        } | to_json }}'
        create: true
        mode: '0644'
      when:
        - log_file is defined
        - enable_rollback | default(true)

    - name: "Primary locale generation failed - continuing with available locales"
      ansible.builtin.debug:
        msg: "Warning: Could not generate primary locale '{{ locale_primary }}'. Continuing with available locales."
      register: primary_locale_gen_result
      failed_when: false

# Display primary locale generation results
# Отображение результатов генерации основной локали
- name: "Display primary locale generation results"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "Primary Locale Generation Results:"
      - "============================================================================="
      - "Primary Locale:         {{ locale_primary }}"
      - "Generation Status:      {{ 'SUCCESS' if primary_locale_gen_result.changed else 'ALREADY GENERATED' }}"
      - "Changed:                {{ 'YES' if primary_locale_gen_result.changed else 'NO' }}"
      - "OS Family:              {{ ansible_os_family }}"
      - "============================================================================="
  when: 
    - debug_mode | default(false)
    - primary_locale_gen_result is defined


# Generate additional locales for multi-language support
# Генерация дополнительных локалей для многоязычной поддержки
- name: "Generate additional locales for multi-language support"
  block:
    - name: "Generate locales"
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ locale_additional }}"
      register: locale_gen_result
      tags:
        - locale
        - generation
        - multi-language
  rescue:
    - name: "Restore locale configuration on failure"
      ansible.builtin.copy:
        src: "{{ item }}{{ backup_suffix }}"
        dest: "{{ item }}"
        remote_src: true
        mode: '0644'
      loop:
        - /etc/locale.gen
      when:
        - enable_rollback | default(true)
        - backup_result is defined
        - backup_result.results is defined
        - item + backup_suffix is file
      register: locale_rollback_result
      failed_when: false

    - name: "Log additional locales generation rollback attempt (structured JSON)"
      # Log additional locales generation rollback attempt
      # Логирование попытки отката генерации дополнительных локалей
      ansible.builtin.lineinfile:
        path: "{{ log_file | default('/var/log/ansible-changes.log') }}"
        line: '{{ {
          "timestamp": ansible_date_time.iso8601,
          "level": "WARN",
          "event_type": "ADDITIONAL_LOCALES_ROLLBACK_ATTEMPTED",
          "user": ansible_user_id,
          "host": inventory_hostname,
          "playbook": ansible_play_name,
          "correlation_id": ansible_date_time.epoch,
          "message": "Additional locales generation failed, rollback attempted",
          "metadata": {
            "rollback_enabled": enable_rollback | default(true),
            "rollback_successful": locale_rollback_result.changed | default(false),
            "failed_locales": locale_additional,
            "primary_locale": locale_primary,
            "os_family": ansible_os_family,
            "os_version": ansible_distribution_version
          }
        } | to_json }}'
        create: true
        mode: '0644'
      when:
        - log_file is defined
        - enable_rollback | default(true)

    - name: "Locale generation failed - continuing with available locales"
      ansible.builtin.debug:
        msg: "Warning: Could not generate some locales. Continuing with available locales."
      register: locale_gen_result
      failed_when: false
  tags:
    - locale
    - generation
    - multi-language


# Configure locale variables in system files
# Настройка переменных локализации в системных файлах
- name: "Configure locale variables in /etc/default/locale"
  block:
    - name: "Configure locale variables"
      ansible.builtin.lineinfile:
        path: /etc/default/locale
        regexp: '^{{ item.key }}=.*$'
        line: '{{ item.key }}="{{ item.value }}"'
        state: present
        create: true
        backup: "{{ backup_enabled }}"
        mode: '0644'
      loop: "{{ locale_variables | dict2items }}"
      register: locale_vars_result
      notify: reload locale
      tags:
        - locale
        - configuration
        - system
        - variables
  rescue:
    - name: "Restore locale variables configuration on failure"
      ansible.builtin.copy:
        src: "{{ item }}{{ backup_suffix }}"
        dest: "{{ item }}"
        remote_src: true
        mode: '0644'
      loop:
        - /etc/default/locale
        - /etc/environment
      when:
        - enable_rollback | default(true)
        - backup_result is defined
        - backup_result.results is defined
        - item + backup_suffix is file
      register: locale_vars_rollback_result
      failed_when: false

      # Log locale variables rollback attempt
      # Логирование попытки отката переменных локализации
    - name: "Log locale variables rollback attempt (structured JSON)"
      ansible.builtin.lineinfile:
        path: "{{ log_file | default('/var/log/ansible-changes.log') }}"
        line: '{{ {
          "timestamp": ansible_date_time.iso8601,
          "level": "WARN",
          "event_type": "LOCALE_VARS_ROLLBACK_ATTEMPTED",
          "user": ansible_user_id,
          "host": inventory_hostname,
          "playbook": ansible_play_name,
          "correlation_id": ansible_date_time.epoch,
          "message": "Locale variables configuration failed, rollback attempted",
          "metadata": {
            "rollback_enabled": enable_rollback | default(true),
            "rollback_successful": locale_vars_rollback_result.changed | default(false),
            "config_files": ["/etc/default/locale", "/etc/environment"],
            "os_family": ansible_os_family,
            "os_version": ansible_distribution_version
          }
        } | to_json }}'
        create: true
        mode: '0644'
      when:
        - log_file is defined
        - enable_rollback | default(true)

    - name: "Locale variables configuration failed"
      ansible.builtin.debug:
        msg: "Error: Could not configure locale variables. Check permissions and file access."
      register: locale_vars_result
      failed_when: false
  tags:
    - locale
    - configuration
    - system
    - variables

# Display detailed locale variables configuration results (English)
# Отображение детальных результатов настройки переменных локализации
- name: "Display detailed locale variables configuration results (English)"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "Locale Variables Configuration Results:"
      - "============================================================================="
      - "Variable:               {{ item.item.key }}"
      - "Value:                  {{ item.item.value }}"
      - "Configuration Changed:  {{ 'YES' if item.changed else 'NO' }}"
      - "File Path:              /etc/default/locale"
      - "Operation Status:       {{ 'SUCCESS' if item.changed else 'NO CHANGE' }}"
      - "============================================================================="
  loop: "{{ locale_vars_result.results | default([]) }}"
  when: 
    - debug_mode | default(false)
    - locale_vars_result is defined
  tags:
    - debug
    - locale
    - variables
    - results

# Configure system timezone
# Настройка системного часового пояса
- name: "Configure system timezone"
  block:
    - name: "Set system timezone"
      community.general.timezone:
        name: "{{ timezone }}"
      register: timezone_result
      notify: reload timezone
      tags:
        - timezone
        - configuration
        - system
  rescue:
      # Log timezone configuration failure
      # Логирование ошибки конфигурации часового пояса
    - name: "Log timezone configuration failure (structured JSON)"
      ansible.builtin.lineinfile:
        path: "{{ log_file | default('/var/log/ansible-changes.log') }}"
        line: '{{ {
          "timestamp": ansible_date_time.iso8601,
          "level": "ERROR",
          "event_type": "TIMEZONE_CONFIG_FAILED",
          "timezone": timezone,
          "user": ansible_user_id,
          "host": inventory_hostname,
          "playbook": ansible_play_name,
          "correlation_id": ansible_date_time.epoch,
          "message": "Timezone configuration failed",
          "metadata": {
            "rollback_enabled": enable_rollback | default(true),
            "timezone_manage": timezone_manage,
            "os_family": ansible_os_family,
            "os_version": ansible_distribution_version,
            "error_type": "INVALID_TIMEZONE"
          }
        } | to_json }}'
        create: true
        mode: '0644'
      when:
        - log_file is defined
        - enable_rollback | default(true)

    - name: "Timezone configuration failed"
      ansible.builtin.debug:
        msg: "Error: Could not configure timezone '{{ timezone }}'. Check if timezone is valid."
      register: timezone_result
      failed_when: false
  when: timezone_manage | bool
  tags:
    - timezone
    - configuration
    - system


# Include configuration tasks
# Включение задач конфигурации
- name: "Include Debian/Ubuntu specific tasks"
  ansible.builtin.include_tasks: debian.yml
  tags:
    - ubuntu
    - os-specific

# Display comprehensive final configuration summary
# Отображение комплексного итогового сводного отчета конфигурации
- name: "Display comprehensive final configuration summary"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "LOCALE CONFIGURATION COMPLETED SUCCESSFULLY!"
      - "============================================================================="
      - "Operating System:      {{ ansible_distribution }} {{ ansible_distribution_version }}"
      - "OS Family:             {{ ansible_os_family }}"
      - "Architecture:          {{ ansible_architecture }}"
      - "Primary Locale:        {{ locale_primary }}"
      - "Timezone:              {{ timezone }}"
      - "Keyboard Layout:       {{ keyboard_layout }}"
      - "Console Font:          {{ console_font }}"
      - "Additional Locales:    {{ locale_additional | length }} configured"
      - "============================================================================="
      - "Configuration Settings:"
      - "- Backup Enabled:      {{ backup_enabled }}"
      - "- Validation Enabled:  {{ validate_parameters }}"
      - "- Debug Mode:          {{ debug_mode }}"
      - "- Strict Validation:   {{ strict_validation }}"
      - "============================================================================="
      - "Operation Results Summary:"
      - "- OS Compatibility:    {{ '✓ SUCCESS' if ansible_os_family == 'Debian' else '✗ FAILED' }}"
      - "- Parameter Validation: {{ '✓ SUCCESS' if validation_result is defined else '⊗ SKIPPED' }}"
      - "- Primary Locale Gen:  {{ '✓ SUCCESS' if primary_locale_gen_result is defined and primary_locale_gen_result.changed else '⊗ SKIPPED' }}"
      - "- Additional Locales:  {{ '✓ SUCCESS' if locale_gen_result is defined and locale_gen_result is success else '⊗ SKIPPED' }}"
      - "- Locale Variables:    {{ '✓ SUCCESS' if locale_vars_result is defined and locale_vars_result.changed else '⊗ NO CHANGE' }}"
      - "- Timezone Config:     {{ '✓ SUCCESS' if timezone_result is defined and timezone_result.changed else '⊗ SKIPPED' }}"
      - "- Packages Installed:  {{ '✓ SUCCESS' if debian_packages_result is defined and ansible_os_family == 'Debian' else '⊗ SKIPPED' }}"
      - "- Keyboard Configured: {{ '✓ SUCCESS' if keyboard_layout_result is defined else '⊗ SKIPPED' }}"
      - "- Console Font Set:    {{ '✓ SUCCESS' if console_font_result is defined and console_font_result.changed else '⊗ SKIPPED' }}"
      - "============================================================================="
      - "Configuration Files Modified:"
      - "- /etc/default/locale"
      - "- /etc/environment"
      - "- /etc/locale.gen"
      - "- /etc/default/console-setup"
      - "- /etc/default/keyboard"
      - "============================================================================="
  when:
    - debug_mode | default(false)
  tags:
    - summary
    - locale
    - completion
    - final