---
# =============================================================================
# SUSE/openSUSE Specific Tasks / Специфичные задачи для SUSE/openSUSE
# =============================================================================
# This file contains tasks specific to SUSE, openSUSE and SLES systems
# Файл содержит задачи, специфичные для систем SUSE, openSUSE и SLES
# =============================================================================

# Install required packages for SUSE / Установка необходимых пакетов для SUSE
- name: "Install required packages for SUSE"
  block:
    - name: "Build package list for SUSE"
      ansible.builtin.set_fact:
        suse_packages_to_install: >-
          {{
            (universal_packages | map('extract', package_mappings.suse) | list) +
            (package_mappings.suse.additional | default([]))
          }}

    - name: "Display packages to install for SUSE"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "SUSE Packages to Install:"
          - "============================================================================="
          - "{{ suse_packages_to_install | join(', ') }}"
          - "============================================================================="
      when: debug_mode | bool

    - name: "Install SUSE packages"
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ suse_packages_to_install }}"
      register: suse_packages_result
  rescue:
    - name: "Log package installation failure (structured JSON)"
      # Log package installation failure
      # Логирование ошибки установки пакетов
      ansible.builtin.lineinfile:
        path: "{{ log_file | default('/var/log/ansible-changes.log') }}"
        line: '{{ {
          "timestamp": ansible_date_time.iso8601,
          "level": "ERROR",
          "event_type": "PACKAGE_INSTALL_FAILED",
          "packages": suse_packages_to_install,
          "user": ansible_user_id,
          "host": inventory_hostname,
          "playbook": ansible_play_name,
          "correlation_id": ansible_date_time.epoch,
          "message": "Package installation failed",
          "metadata": {
            "rollback_enabled": enable_rollback | default(true),
            "os_family": ansible_os_family,
            "os_version": ansible_distribution_version,
            "package_manager": "zypper",
            "error_type": "PACKAGE_INSTALL_ERROR"
          }
        } | to_json }}'
        create: true
        mode: '0644'
      when:
        - log_file is defined
        - enable_rollback | default(true)

    - name: "Package installation failed"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "SUSE Package Installation Error:"
          - "============================================================================="
          - "Error: Could not install required packages."
          - "Some features may not work properly."
          - "Ошибка: Не удалось установить необходимые пакеты."
          - "Некоторые функции могут работать неправильно."
          - "============================================================================="
      register: suse_packages_result
      failed_when: false

# Display SUSE package installation results / Отображение результатов установки пакетов SUSE
- name: "Display SUSE package installation results"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "SUSE Package Installation Results:"
      - "============================================================================="
      - "Package:                {{ item.item }}"
      - "Installation Status:    {{ 'SUCCESS' if item.changed else 'ALREADY INSTALLED' }}"
      - "Changed:                {{ 'YES' if item.changed else 'NO' }}"
      - "Return Code:            {{ item.rc | default('N/A') }}"
      - "============================================================================="
  loop: "{{ suse_packages_result.results | default([]) }}"
  no_log: true
  when: 
    - debug_mode | bool
    - suse_packages_result is defined
    - suse_packages_result.results is defined

# Configure keyboard layout for SUSE systems / Настройка раскладки клавиатуры для систем SUSE
- name: "Configure keyboard layout for SUSE"
  block:
    - name: "Set keyboard layout"
      ansible.builtin.command: "localectl set-keymap {{ keyboard_layout }}"
      register: keyboard_layout_result
      changed_when: keyboard_layout_result.rc == 0
  rescue:
    - name: "Keyboard layout configuration failed"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "SUSE Keyboard Configuration Error:"
          - "============================================================================="
          - "Error: Could not configure keyboard layout '{{ keyboard_layout }}'."
          - "Ошибка: Не удалось настроить раскладку клавиатуры '{{ keyboard_layout }}'."
          - "============================================================================="
      register: keyboard_layout_result
      failed_when: false
  when: keyboard_layout != ""

# Configure keyboard variant for SUSE / Настройка варианта клавиатуры для SUSE
- name: "Configure keyboard variant for SUSE"
  ansible.builtin.command: "localectl set-x11-keymap {{ keyboard_layout }} {{ keyboard_variant }}"
  when: keyboard_variant != ""
  register: keyboard_variant_result
  failed_when: false
  changed_when: keyboard_variant_result.rc == 0

# Configure keyboard options for SUSE / Настройка опций клавиатуры для SUSE
- name: "Configure keyboard options for SUSE"
  ansible.builtin.command: "localectl set-x11-keymap {{ keyboard_layout }} {{ keyboard_variant }} {{ keyboard_options }}"
  when: keyboard_options != ""
  register: keyboard_options_result
  failed_when: false
  changed_when: keyboard_options_result.rc == 0

# Display keyboard configuration results for SUSE / Отображение результатов настройки клавиатуры для SUSE
- name: "Display keyboard configuration results for SUSE"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "SUSE Keyboard Configuration Results:"
      - "============================================================================="
      - "Layout:                 {{ keyboard_layout }}"
      - "Variant:                {{ keyboard_variant }}"
      - "Options:                {{ keyboard_options }}"
      - "Layout Changed:         {{ 'YES' if keyboard_layout_result.changed | default(false) else 'NO' }}"
      - "Variant Changed:        {{ 'YES' if keyboard_variant_result.changed | default(false) else 'NO' }}"
      - "Options Changed:        {{ 'YES' if keyboard_options_result.changed | default(false) else 'NO' }}"
      - "Layout Return Code:     {{ keyboard_layout_result.rc | default('N/A') }}"
      - "Variant Return Code:    {{ keyboard_variant_result.rc | default('N/A') }}"
      - "Options Return Code:    {{ keyboard_options_result.rc | default('N/A') }}"
      - "============================================================================="
  when: debug_mode | bool

# Configure console font for SUSE / Настройка консольного шрифта для SUSE
- name: "Configure console font for SUSE"
  ansible.builtin.lineinfile:
    path: /etc/vconsole.conf
    regexp: '^FONT=.*$'
    line: 'FONT="{{ console_font }}"'
    state: present
    create: true
    backup: "{{ backup_enabled }}"
    mode: '0644'
  when: console_font_manage | bool
  register: console_font_result
  notify: reload console
  failed_when: false

# Display console font configuration results for SUSE / Отображение результатов настройки консольного шрифта для SUSE
- name: "Display console font configuration results for SUSE"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "SUSE Console Font Configuration Results:"
      - "============================================================================="
      - "Font:                   {{ console_font }}"
      - "Configuration Changed:  {{ 'YES' if console_font_result.changed | default(false) else 'NO' }}"
      - "File Path:              /etc/vconsole.conf"
      - "Operation Status:       {{ 'SUCCESS' if console_font_result.changed | default(false) else 'NO CHANGE' }}"
      - "============================================================================="
  when: 
    - debug_mode | bool
    - console_font_result is defined

# Configure system locale using localectl for SUSE / Настройка системной локали с помощью localectl для SUSE
- name: "Configure system locale using localectl for SUSE"
  block:
    - name: "Set system locale"
      ansible.builtin.command: "localectl set-locale LANG={{ locale_primary }}"
      register: suse_locale_result
      changed_when: suse_locale_result.rc == 0
      notify: reload locale
  rescue:
    - name: "System locale configuration failed"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "SUSE Locale Configuration Error:"
          - "============================================================================="
          - "Error: Could not configure system locale '{{ locale_primary }}'."
          - "Ошибка: Не удалось настроить системную локаль '{{ locale_primary }}'."
          - "============================================================================="
      register: suse_locale_result
      failed_when: false

# Display SUSE locale configuration results / Отображение результатов настройки локали для SUSE
- name: "Display SUSE locale configuration results"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "SUSE Locale Configuration Results:"
      - "============================================================================="
      - "Primary Locale:         {{ locale_primary }}"
      - "Configuration Changed:  {{ 'YES' if suse_locale_result.changed | default(false) else 'NO' }}"
      - "Return Code:            {{ suse_locale_result.rc | default('N/A') }}"
      - "Output:                 {{ suse_locale_result.stdout | default('N/A') }}"
      - "Errors:                 {{ suse_locale_result.stderr | default('N/A') }}"
      - "============================================================================="
  when: 
    - debug_mode | bool
    - suse_locale_result is defined

