---
# Locale configuration
# Конфигурация локали

# Boolean. Enable change notifications in debug output.
# Логическое значение. Включает уведомления об изменениях в debug-выводе.
set_locale_debug_mode: false

# String. Locale generated and configured as the system language.
# Строка. Локаль, генерируемая и настраиваемая как язык системы.
set_locale_name: "en_US.UTF-8"
