---
# Debian Package Installation Role Defaults
# Значения по умолчанию для роли установки пакетов Debian
# This role installs essential packages for Ubuntu/Debian systems
# Эта роль устанавливает основные пакеты для систем Ubuntu/Debian

# Debug mode for verbose output / Режим отладки для подробного вывода
debug_mode: false
# Log file for structured logging / Файл лога для структурированного логирования
log_file: "/var/log/ansible-changes.log"
# Validation settings / Настройки валидации
validate_parameters: true
verify_deployment: true                 # Boolean. Enable post-deployment verification
                                        # Логическое значение. Включить проверку пост-развертывания

# Universal package cache management / Универсальное управление кэшем пакетов
package_cache_valid_time: 86400  # 24 hours in seconds / 24 часа в секундах
package_update_cache: true       # Update package cache / Обновлять кэш пакетов
package_upgrade_packages: true   # Upgrade system packages / Обновлять системные пакеты

# Essential packages list for Debian/Ubuntu systems
# Список основных пакетов для систем Debian/Ubuntu
essential_packages:
  - acl                    # Access Control Lists / Списки контроля доступа
  - sudo                   # Superuser do / Выполнение от имени суперпользователя
  - net-tools              # Network utilities / Сетевые утилиты
  - gnupg                  # GNU Privacy Guard / GNU Privacy Guard
  - htop                   # Interactive process viewer / Интерактивный просмотрщик процессов
  - curl                   # Command line tool for transferring data / Инструмент командной строки для передачи данных
  - wget                   # Internet file retriever / Загрузчик файлов из интернета
  - openssh-client         # SSH client / SSH клиент
  - iputils-ping           # Network testing tools / Инструменты тестирования сети
  - dnsutils               # DNS utilities / DNS утилиты
  - apt-transport-https    # HTTPS transport for APT / HTTPS транспорт для APT
  - software-properties-common  # Software properties management / Управление свойствами ПО

# Universal optional packages that can be added by users
# Универсальные дополнительные пакеты, которые могут быть добавлены пользователями
optional_packages: []

# Whether to install recommended packages
# Устанавливать ли рекомендуемые пакеты
package_install_recommends: true

# =============================================================================
# Automatic Security Updates Configuration
# Конфигурация автоматических обновлений безопасности
# =============================================================================

# Enable automatic security updates / Включить автоматические обновления безопасности
autoupdates_enabled: false

# Install only security updates (not all available updates)
# Устанавливать только обновления безопасности (не все доступные обновления)
security_updates_only: true

# Allow automatic system reboot if required after updates
# Разрешить автоматическую перезагрузку системы, если требуется после обновлений
reboot_if_required: false

# Require GPG signature verification for all packages
# Требовать проверку GPG подписи для всех пакетов
gpg_require_signed: true

# Automatic removal of unused dependencies (Debian/Ubuntu only)
# Автоматическое удаление неиспользуемых зависимостей (только Debian/Ubuntu)
autoupdates_autoremove: true

# Automatic update schedule configuration / Конфигурация расписания автоматических обновлений
# For Debian/Ubuntu: unattended-upgrades runs via apt.systemd.daily
autoupdates_schedule_enabled: true

# Time for automatic updates (for systems that support it)
# Время для автоматических обновлений (для систем, которые это поддерживают)
autoupdates_time: "02:00"

# Download updates automatically even if not installing
# Загружать обновления автоматически, даже если не устанавливать
autoupdates_download_only: false

# =============================================================================
# System Requirements
# Системные требования
# =============================================================================

# Minimum disk space required for installation (in bytes)
# Минимальное дисковое пространство необходимое для установки (в байтах)
min_disk_space: 1073741824              # Integer. Minimum disk space in bytes (1GB)
                                        # Целое число. Минимальное дисковое пространство в байтах (1ГБ)

# Minimum memory required for installation (in MB)
# Минимальная память необходимая для установки (в МБ)
min_memory_mb: 512                      # Integer. Minimum memory in MB
                                        # Целое число. Минимальная память в МБ

# Required mount points for preflight checks
# Необходимые точки монтирования для предварительных проверок
required_mounts: ["/"]                  # List. Required mount points
                                        # Список. Необходимые точки монтирования
