---
# =============================================================================
# AdGuard Home - Binary Installation
# AdGuard Home - Установка бинарника
# =============================================================================

- name: Ensure AdGuard Home bin directory exists
  ansible.builtin.file:
    dest: "{{ adguard_bin_dir }}"
    recurse: true
    state: directory

- name: Create AdGuard Home temporary directory
  ansible.builtin.file:
    dest: "{{ adguard_unpack_dir }}"
    recurse: true
    state: directory

- name: "Download and extract AdGuard Home (v{{ adguard_version }} / {{ adguard_arch }})"
  ansible.builtin.unarchive:
    src: "{{ adguard_download_url_base }}/v{{ adguard_version }}/{{ adguard_archive }}"
    dest: "{{ adguard_unpack_dir }}"
    remote_src: true
    extra_opts:
      - "--strip-components=1"

- name: Debug - show copy paths
  ansible.builtin.debug:
    msg: "Copy files from {{ adguard_unpack_dir }}/{{ adguard_bin_name }} to {{ adguard_bin_dir }}/"
  when: debug_mode | default(false)

- name: "Copy AdGuard Home binary to {{ adguard_bin_dir }}/"
  ansible.builtin.copy:
    src: "{{ adguard_unpack_dir }}/{{ adguard_bin_name }}/"
    dest: "{{ adguard_bin_dir }}"
    mode: "0755"
    remote_src: true
    force: true
  notify: restart adguardhome

- name: Remove AdGuard Home temporary directory
  ansible.builtin.file:
    path: "{{ adguard_unpack_dir }}"
    state: absent
