---

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: "{{ apt_upgrade_packages }}"
    update_cache: "{{ apt_update_cache }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Install essential packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present