
---

###  In environments like Docker containers, direct modification of host kernel parameters like kernel.randomize_va_space is often restricted or not possible, as containers share the host's kernel.

- name: Enable Address Space Layout Randomization
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: "{{ sysctl_key }}"
    state: present
    sysctl_set: True
    reload: True

- name: Kernel module loading protection
  ansible.posix.sysctl:
    name: kernel.modules_disabled
    value: 1
    state: present
    sysctl_set: True
    reload: True


## Warning! ##
## Сделай проверку на установку auditd для siem

- name: Restrict chmod 777 with auditd command
  ansible.builtin.lineinfile:
    dest: /etc/audit/rules.d/audit.rules
    regexp: '-w /bin/chmod'
    line: '-w /bin/chmod -p x -k chmod_watch'

- name: Set permissions on /etc/shadow
  ansible.builtin.file:
    path: /etc/shadow
    owner: root
    group: shadow
    mode: '0640'

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
    state: present
    backup: True

- name: Disable empty passwords in SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'

- name: Restrict SSH access by IP subnet
  ansible.builtin.lineinfile:
    path: /etc/hosts.allow
    line: "sshd: {{ allowed_ssh_subnet }}"
    create: True
  loop: "{{ allowed_ssh_subnet }}"
  notify: Restart sshd