---
# =============================================================================
# SUSE/openSUSE Automatic Security Updates Configuration
# =============================================================================
# This file configures zypper automatic updates for security patches
# with GPG verification and trusted key management.
#
# Этот файл настраивает автоматические обновления zypper для патчей безопасности
# с проверкой GPG и управлением доверенными ключами.
# =============================================================================

# Configure zypper for automatic security updates
# Настройка zypper для автоматических обновлений безопасности
- name: "Configure automatic security updates for SUSE/openSUSE"
  block:
    # Show initialization message
    # Показать сообщение об инициализации
    - name: "Display automatic updates configuration initialization (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "Configuring Automatic Security Updates for SUSE/openSUSE"
          - "============================================================================="
          - "Distribution:             {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
          - "Auto-updates Enabled:     {{ autoupdates_enabled }}"
          - "Security Only:            {{ security_updates_only }}"
          - "GPG Verification:         {{ gpg_require_signed }}"
          - "Reboot If Required:       {{ reboot_if_required }}"
          - "============================================================================="
      when: 
        - debug_mode | bool

    # Install tools for configuring automatic updates
    # Установка инструментов для настройки автоматических обновлений
    - name: "Install yast2-online-update-configuration for automatic updates"
      community.general.zypper:
        name:
          - yast2-online-update-configuration
          - zypper-needs-restarting
        state: present
      register: autoupdate_install
      become: true
      failed_when: false
      tags:
        - packages
        - security
        - autoupdate

    # Log automatic updates tools installation
    # Логирование установки инструментов автоматических обновлений
    - name: "Log automatic updates tools installation"
      ansible.builtin.lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }} | PACKAGE_INSTALL | AUTOUPDATE_TOOLS | {{ ansible_hostname }} | {{ 'SUCCESS' if autoupdate_install.changed else 'NO_CHANGE' }} | yast2-online-update-configuration, zypper-needs-restarting"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: autoupdate_install is defined

    # Check that all repositories have valid GPG keys
    # Проверка наличия валидных GPG ключей для всех репозиториев
    - name: "Verify GPG keys for all configured repositories"
      ansible.builtin.command: rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
      register: rpm_keys_list
      changed_when: false
      failed_when: false
      become: true
      tags:
        - security
        - gpg

    # Get list of all configured repositories
    # Получение списка всех настроенных репозиториев
    - name: "List all configured repositories"
      ansible.builtin.command: zypper repos --uri
      register: zypper_repos_list
      changed_when: false
      failed_when: false
      become: true
      tags:
        - security

    # Show GPG keys status
    # Показать статус GPG ключей
    - name: "Display GPG keys verification status (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "GPG Keys Verification:"
          - "============================================================================="
          - "GPG Keys Found:           {{ 'YES' if rpm_keys_list.rc == 0 else 'NO' }}"
          - "Keys Count:               {{ rpm_keys_list.stdout_lines | length }}"
          - "Repositories Count:       {{ (zypper_repos_list.stdout_lines | select('match', '^\\s*[0-9]+\\s+\\|') | list | length) if zypper_repos_list.rc == 0 else 'Unknown' }}"
          - "Verification Status:      {{ 'PASSED' if rpm_keys_list.rc == 0 else 'FAILED' }}"
          - "============================================================================="
      when: 
        - debug_mode | bool


    # Ensure Zypper only accepts signed packages
    # Обеспечить принятие Zypper только подписанных пакетов
    - name: "Configure Zypper to require signed packages"
      ansible.builtin.lineinfile:
        path: /etc/zypp/zypp.conf
        regexp: '^gpgcheck\s*='
        line: 'gpgcheck = on'
        create: true
        mode: '0644'
        owner: root
        group: root
      become: true
      when: gpg_require_signed | bool
      tags:
        - security
        - gpg
        - configuration

    # Configure automatic import of trusted repository GPG keys
    # Настройка автоматического импорта доверенных GPG ключей репозиториев
    - name: "Configure Zypper to auto-import repository GPG keys"
      ansible.builtin.lineinfile:
        path: /etc/zypp/zypp.conf
        regexp: '^repo.refresh.locales\s*='
        line: 'repo.refresh.locales = auto'
        create: true
        mode: '0644'
        owner: root
        group: root
      become: true
      when: gpg_require_signed | bool
      tags:
        - security
        - gpg
        - configuration

    # Import and trust GPG keys for all enabled repositories
    # Импорт и установка доверия GPG ключам для всех включенных репозиториев
    - name: "Ensure all repository GPG keys are imported and trusted"
      ansible.builtin.command: zypper --gpg-auto-import-keys refresh
      register: zypper_refresh_keys
      changed_when: "'Retrieving' in zypper_refresh_keys.stdout"
      failed_when: false
      become: true
      tags:
        - security
        - gpg

    # Create custom systemd service for automatic security updates
    # Создание пользовательского systemd сервиса для автоматических обновлений безопасности
    - name: "Create systemd service for automatic updates"
      ansible.builtin.template:
        src: zypper-automatic-update.service.j2
        dest: /etc/systemd/system/zypper-automatic-update.service
        mode: '0644'
        owner: root
        group: root
      become: true
      register: zypper_service_file
      tags:
        - configuration
        - security

    # Log zypper automatic update service configuration
    # Логирование конфигурации сервиса автоматических обновлений zypper
    - name: "Log zypper automatic update service configuration"
      ansible.builtin.lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }} | CONFIG_CHANGE | ZYPPER_SERVICE | {{ ansible_hostname }} | {{ 'SUCCESS' if zypper_service_file.changed else 'NO_CHANGE' }} | Service: zypper-automatic-update.service"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: zypper_service_file is defined

    # Create systemd timer to schedule automatic updates
    # Создание systemd таймера для планирования автоматических обновлений
    - name: "Create systemd timer for automatic updates"
      ansible.builtin.template:
        src: zypper-automatic-update.timer.j2
        dest: /etc/systemd/system/zypper-automatic-update.timer
        mode: '0644'
        owner: root
        group: root
      become: true
      register: zypper_timer_file
      tags:
        - configuration
        - security

    # Log zypper automatic update timer configuration
    # Логирование конфигурации таймера автоматических обновлений zypper
    - name: "Log zypper automatic update timer configuration"
      ansible.builtin.lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }} | CONFIG_CHANGE | ZYPPER_TIMER | {{ ansible_hostname }} | {{ 'SUCCESS' if zypper_timer_file.changed else 'NO_CHANGE' }} | Timer: zypper-automatic-update.timer, Schedule: {{ autoupdates_time }}"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: zypper_timer_file is defined

    # Create script to perform automatic security updates
    # Создание скрипта для выполнения автоматических обновлений безопасности
    - name: "Create automatic update script"
      ansible.builtin.template:
        src: zypper-automatic-update.sh.j2
        dest: /usr/local/bin/zypper-automatic-update.sh
        mode: '0755'
        owner: root
        group: root
      become: true
      register: zypper_script_file
      tags:
        - configuration
        - security

    # Reload systemd to pick up new service and timer
    # Перезагрузка systemd для применения нового сервиса и таймера
    - name: "Reload systemd daemon after service/timer changes"
      ansible.builtin.systemd:
        daemon_reload: true
      become: true
      when: zypper_service_file.changed or zypper_timer_file.changed
      tags:
        - service

    # Ensure automatic updates timer is enabled and running
    # Обеспечить включение и запуск таймера автоматических обновлений
    - name: "Enable and start automatic updates timer"
      ansible.builtin.systemd:
        name: zypper-automatic-update.timer
        enabled: true
        state: started
      become: true
      register: zypper_timer_service
      tags:
        - service
        - security

    # Show configuration results
    # Показать результаты конфигурации
    - name: "Display automatic updates configuration results (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "Automatic Security Updates Configuration Results:"
          - "============================================================================="
          - "Packages Installed:       {{ 'YES' if autoupdate_install.changed else 'ALREADY INSTALLED' }}"
          - "Service Created:          {{ 'YES' if zypper_service_file.changed else 'NO CHANGE' }}"
          - "Timer Created:            {{ 'YES' if zypper_timer_file.changed else 'NO CHANGE' }}"
          - "Script Created:           {{ 'YES' if zypper_script_file.changed else 'NO CHANGE' }}"
          - "Timer Enabled:            {{ 'YES' if zypper_timer_service.changed else 'ALREADY ENABLED' }}"
          - "GPG Check Enabled:        {{ gpg_require_signed }}"
          - "Configuration Status:     SUCCESS"
          - "============================================================================="
      when: 
        - debug_mode | bool


  when: autoupdates_enabled | bool
  rescue:
    # Handle any errors that occur during configuration
    # Обработка любых ошибок, возникающих при конфигурации
    - name: "Handle automatic updates configuration errors"
      ansible.builtin.debug:
        msg: "Warning: Failed to configure automatic security updates. Manual configuration may be required."

