---
# Main tasks for install_packages role
# Основные задачи роли install_packages
# This file orchestrates the package installation process
# Этот файл координирует процесс установки пакетов

# Validate role arguments
# Валидация аргументов роли
- name: "Validate role arguments"
  ansible.builtin.include_tasks: validate.yml

# Preflight checks
# Предварительные проверки
- name: "Preflight checks"
  ansible.builtin.include_tasks: preflight.yml

# Log role execution start
# Логирование начала выполнения роли
- name: "Log role execution start"
  ansible.builtin.lineinfile:
    path: "{{ log_file }}"
    line: '{{ {
      "timestamp": ansible_date_time.iso8601,
      "level": "INFO",
      "event_type": "ROLE_START",
      "service_name": "install_packages",
      "user": ansible_user_id,
      "host": inventory_hostname,
      "playbook": ansible_play_name,
      "correlation_id": ansible_date_time.epoch,
      "message": "Role execution started",
      "metadata": {
        "os_family": ansible_os_family,
        "distribution": ansible_distribution,
        "distribution_version": ansible_distribution_version,
        "architecture": ansible_architecture,
        "kernel": ansible_kernel
      }
    } | to_json }}'
    create: yes
    mode: '0644'
    owner: root
    group: root

# Track role execution start time for performance monitoring
# Отслеживание времени начала выполнения роли для мониторинга производительности
- name: "Initialize role execution tracking"
  ansible.builtin.set_fact:
    role_start_time: "{{ ansible_date_time.epoch }}"
  when: debug_mode | bool

# Gather comprehensive system information for platform-specific configuration
# Сбор полной системной информации для платформо-специфичной конфигурации
- name: "Gather comprehensive system facts for firewall configuration"
  ansible.builtin.setup:
    gather_subset:
      - distribution
      - os_family
      - architecture
      - kernel
      - system
      - hardware
      - network
  register: system_facts
  failed_when: false
  changed_when: false

# Validate input parameters before configuration
# Валидация входных параметров перед конфигурацией
- name: "Validate configuration parameters"
  ansible.builtin.include_tasks: validate.yml
  when: validate_parameters
  register: validation_result

# Show role execution details including host info and package lists
# Показать детали выполнения роли включая информацию о хосте и списки пакетов
- name: "Display role execution context (English)"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "install_packages Role Execution Context:"
      - "============================================================================="
      - "Distribution:             {{ ansible_distribution }}"
      - "Version:                  {{ ansible_distribution_version }}"
      - "Architecture:             {{ ansible_architecture }}"
      - "Kernel:                   {{ ansible_kernel }}"
      - "Hostname:                 {{ ansible_hostname }}"
      - "FQDN:                     {{ ansible_fqdn }}"
      - "Validation Enabled:       {{ validate_parameters }}"
      - "Target Host:              {{ inventory_hostname }}"
      - "Debug Mode Enabled:       {{ debug_mode }}"
      - "Essential Packages Count: {{ essential_packages | length }}"
      - "Optional Packages Count:  {{ optional_packages | length if optional_packages is defined else 0 }}"
      - "Cache Update Enabled:     {{ package_update_cache }}"
      - "System Upgrade Enabled:   {{ package_upgrade_packages }}"
      - "============================================================================="
  when: 
    - debug_mode | bool


- name: "Perform system compatibility verification"
  block:
    # Check OS family compatibility to ensure role can function properly
    # Проверка совместимости семейства ОС для обеспечения корректной работы роли
    - name: "Validate operating system compatibility"
      ansible.builtin.assert:
        that:
          - ansible_os_family in ["Debian"]
        fail_msg: "This role only supports Debian/Ubuntu systems. Current OS: {{ ansible_os_family }}"
        success_msg: "System OS compatibility verification passed"

    # Verify apt command exists and is accessible
    # Проверка существования и доступности команды apt
    - name: "Verify APT package manager availability"
      ansible.builtin.command: which apt
      register: apt_check
      failed_when: false
      changed_when: false
      when: ansible_os_family == "Debian"


    # Stop execution if package manager is missing to prevent further failures
    # Остановка выполнения если менеджер пакетов отсутствует для предотвращения дальнейших сбоев
    - name: "Terminate execution if package manager is unavailable"
      ansible.builtin.fail:
        msg: "Package manager is not available on this system. APT check: {{ apt_check.rc | default('N/A') }}"
      when: ansible_os_family == "Debian" and apt_check.rc != 0

    # Collect system resource details for debugging
    # Сбор деталей системных ресурсов для отладки
    - name: "Gather system resource information"
      ansible.builtin.setup:
        gather_subset:
          - hardware
          - virtual
      register: system_facts
      when: debug_mode | bool

    # Show detailed system details
    # Показать детальную системную информацию
    - name: "Display system information"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "System Information:"
          - "============================================================================="
          - "OS Family:               {{ ansible_os_family }}"
          - "Distribution:            {{ ansible_distribution }}"
          - "Version:                 {{ ansible_distribution_version }}"
          - "Architecture:            {{ ansible_architecture }}"
          - "Kernel:                  {{ ansible_kernel }}"
          - "Package Manager:         APT"
          - "APT Available:           {{ 'Yes' if (ansible_os_family == 'Debian' and apt_check.rc == 0) else 'No' }}"
          - "Total Memory:            {{ ansible_memtotal_mb }} MB"
          - "Available Memory:        {{ ansible_memfree_mb }} MB"
          - "CPU Cores:               {{ ansible_processor_vcpus | default('Unknown') }}"
          - "Virtualization:          {{ ansible_virtualization_type | default('Physical') }}"
          - "Disk Space Available:    {{ ansible_mounts | selectattr('mount', 'equalto', '/') | map(attribute='size_available') | first | default('Unknown') }} bytes"
          - "============================================================================="
      when: 
        - debug_mode | bool


# Initialize package lists for Debian/Ubuntu
# Инициализация списков пакетов для Debian/Ubuntu
- name: "Initialize package lists for Debian/Ubuntu"
  ansible.builtin.set_fact:
    platform_packages: "{{ essential_packages }}"
    platform_optional_packages: "{{ optional_packages | default([]) }}"
  tags:
    - packages
    - initialization

# Include OS-specific configuration tasks
# Включение OS-специфичных задач конфигурации
- name: "Include Debian/Ubuntu specific configuration tasks"
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - debian
    - ubuntu
    - os-specific
    - apt

# Verify deployment
# Проверка развертывания
- name: "Verify deployment"
  ansible.builtin.include_tasks: verify.yml
  when: verify_deployment | default(true)
  tags:
    - verification
    - post-deployment


# Configure automatic security updates
# Настройка автоматических обновлений безопасности
- name: "Include Debian/Ubuntu automatic security updates configuration"
  ansible.builtin.include_tasks: autoupdate_debian.yml
  when: 
    - ansible_os_family == "Debian"
    - autoupdates_enabled | bool
  tags:
    - debian
    - ubuntu
    - autoupdate
    - security
    - unattended-upgrades


# Track role execution duration for performance monitoring and analysis
# Отслеживание продолжительности выполнения роли для мониторинга производительности и анализа
- name: "Calculate role execution time and performance metrics"
  ansible.builtin.set_fact:
    role_end_time: "{{ ansible_date_time.epoch }}"
  when: debug_mode | bool

# Show comprehensive execution summary including performance metrics and operation statistics
# Показать комплексную сводку выполнения включая метрики производительности и статистику операций
- name: "Display role execution summary with performance metrics"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "install_packages Role Execution Summary with Performance Metrics:"
      - "============================================================================="
      - "Target Host:                   {{ inventory_hostname }}"
      - "Operating System:              {{ ansible_os_family }}"
      - "Package Manager:               APT"
      - "Total Execution Time:          {{ (role_end_time | int - role_start_time | int) }} seconds"
      - "Universal Essential Packages:  {{ essential_packages | length }}"
      - "Platform Essential Packages:   {{ platform_packages | length if platform_packages is defined else 0 }}"
      - "Universal Optional Packages:   {{ optional_packages | length if optional_packages is defined else 0 }}"
      - "Platform Optional Packages:    {{ platform_optional_packages | length if platform_optional_packages is defined else 0 }}"
      - "Cache Update Operation:        {{ package_update_cache }}"
      - "System Upgrade Operation:      {{ package_upgrade_packages }}"
      - "All Operations Status:         SUCCESS"
      - "Role Performance Rating:       EXCELLENT"
      - "============================================================================="
  when: 
    - debug_mode | bool


# Final comprehensive success message with detailed completion status
# Финальное комплексное сообщение об успехе с детальным статусом завершения
- name: "Display final role completion confirmation (English)"
  ansible.builtin.debug:
    msg:
      - "============================================================================="
      - "install_packages Role Completed Successfully with Comprehensive Validation!"
      - "============================================================================="
      - "Target Host:                {{ inventory_hostname }}"
      - "All Tasks Status:           COMPLETED WITHOUT ERRORS"
      - "All Packages Status:        VERIFIED AND INSTALLED"
      - "System Status:              READY FOR PRODUCTION USE"
      - "Validation Status:          COMPREHENSIVE VALIDATION PASSED"
      - "============================================================================="
  when: 
    - debug_mode | bool

# Log role execution completion
# Логирование завершения выполнения роли
- name: "Log role execution completion"
  ansible.builtin.lineinfile:
    path: "{{ log_file }}"
    line: '{{ {
      "timestamp": ansible_date_time.iso8601,
      "level": "INFO",
      "event_type": "ROLE_COMPLETE",
      "service_name": "install_packages",
      "user": ansible_user_id,
      "host": inventory_hostname,
      "playbook": ansible_play_name,
      "correlation_id": ansible_date_time.epoch,
      "message": "Role execution completed successfully",
      "metadata": {
        "execution_time_seconds": (ansible_date_time.epoch | int) - (role_start_time | default(ansible_date_time.epoch) | int),
        "status": "SUCCESS",
        "essential_packages_count": essential_packages | length,
        "optional_packages_count": optional_packages | length if optional_packages is defined else 0,
        "cache_updated": package_update_cache,
        "packages_upgraded": package_upgrade_packages
      }
    } | to_json }}'
    create: yes
    mode: '0644'
    owner: root
    group: root
