---
# =============================================================================
# SUSE/openSUSE Specific Package Installation Tasks
# =============================================================================
# This file contains SUSE/openSUSE specific package installation tasks
# for Zypper package manager.
#
# Этот файл содержит специфичные для SUSE/openSUSE задачи установки пакетов
# для менеджера пакетов Zypper.
# =============================================================================

# Execute Zypper package cache management and repository synchronization
# Выполнение управления кэшем пакетов Zypper и синхронизации репозиториев
- name: "Execute Zypper package cache management and repository synchronization"
  block:      # Refresh package repository information
      # Обновление информации о репозиториях пакетов

    - name: "Refresh Zypper package cache"
      community.general.zypper:
        update_cache: "{{ package_update_cache }}"
      register: zypper_update_result
      when: package_update_cache | bool

    # Log package cache update operation
    # Логирование операции обновления кэша пакетов
    - name: "Log Zypper package cache update"
      ansible.builtin.lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }} | CACHE_UPDATE | ZYPPER | {{ ansible_hostname }} | {{ 'SUCCESS' if zypper_update_result.changed else 'NO_CHANGE' }} | {{ zypper_update_result.changed | default(false) }}"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: 
        - package_update_cache | bool
        - zypper_update_result is defined      # Verify repository availability
      # Проверка доступности репозиториев


    - name: "Check available Zypper repositories"
      ansible.builtin.command: zypper repos
      register: zypper_repositories
      failed_when: false
      changed_when: false
      when: debug_mode | bool      # Show detailed cache update status and repository information
      # Показать детальный статус обновления кэша и информацию о репозиториях


    - name: "Display Zypper cache update and repository analysis results (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "Zypper Cache Update and Repository Analysis Results:"
          - "============================================================================="
          - "Cache Updated:            {{ zypper_update_result.changed | default(false) }}"
          - "Update Cache Enabled:     {{ package_update_cache }}"
          - "Available Repositories:   {{ zypper_repositories.stdout_lines | length if zypper_repositories is defined else 'Unknown' }}"
          - "Operation Status:         {{ 'SUCCESS' if zypper_update_result.changed else 'NO CHANGE' }}"
          - "============================================================================="
      when: 
        - debug_mode | bool and package_update_cache | bool
# Execute comprehensive system package upgrade and maintenance for SUSE/openSUSE
# Выполнение комплексного обновления и обслуживания системных пакетов для SUSE/openSUSE
- name: "Execute system package upgrade and maintenance for SUSE/openSUSE"
  block:      # Update installed packages to latest versions with configurable upgrade policy
      # Обновление установленных пакетов до последних версий с настраиваемой политикой обновления

    - name: "Perform system-wide package upgrade to latest available versions"
      community.general.zypper:
        name: "*"
        state: latest
      register: zypper_upgrade_result
      when: package_upgrade_packages | bool      # Show comprehensive upgrade operation status and impact
      # Показать комплексный статус операции обновления и её влияние


    - name: "Display system package upgrade operation results (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "System Package Upgrade Operation Results:"
          - "============================================================================="
          - "Packages Upgraded:        {{ zypper_upgrade_result.changed | default(false) }}"
          - "Upgrade Policy Enabled:   {{ package_upgrade_packages }}"
          - "Operation Status:         {{ 'SUCCESS' if zypper_upgrade_result.changed else 'NO CHANGE' }}"
          - "Upgrade Completed:        YES"
          - "============================================================================="
      when: 
        - debug_mode | bool and package_upgrade_packages | bool
# Execute essential package installation with comprehensive pre-installation analysis for SUSE/openSUSE
# Выполнение установки основных пакетов с комплексным предустановочным анализом для SUSE/openSUSE
- name: "Execute essential package installation with pre-installation analysis for SUSE/openSUSE"
  block:      # Collect detailed package information for installation planning
      # Сбор детальной информации о пакетах для планирования установки

    - name: "Gather comprehensive information about currently installed packages"
      ansible.builtin.package_facts:
        manager: auto
      register: package_facts      # Verify packages are available for installation with version information
      # Проверка доступности пакетов для установки с информацией о версиях


    - name: "Perform detailed package availability verification in repositories"
      ansible.builtin.command: "zypper search --match-exact {{ item }}"
      register: package_availability
      failed_when: false
      changed_when: false
      loop: "{{ platform_packages }}"
      when: debug_mode | bool      # Show detailed package availability information including versions
      # Показать детальную информацию о доступности пакетов включая версии


    - name: "Display package availability analysis results (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "Package Availability Analysis:"
          - "============================================================================="
          - "Package Name:             {{ item.item }}"
          - "Available in Repos:       {{ 'YES' if item.rc == 0 else 'NO' }}"
          - "Status:                   {{ 'AVAILABLE' if item.rc == 0 else 'NOT FOUND' }}"
          - "============================================================================="
      loop: "{{ package_availability.results | default([]) }}"
      when: 
        - debug_mode | bool and package_availability is defined      # Show comprehensive package installation status and planning information
      # Показать комплексный статус установки пакетов и информацию о планировании

    - name: "Display current package installation status and installation plan (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "Current Package Installation Status and Installation Plan:"
          - "============================================================================="
          - "Total Installed Packages:  {{ package_facts.ansible_facts.packages | length }}"
          - "Essential Already Installed: {{ platform_packages | intersect(package_facts.ansible_facts.packages.keys()) | list }}"
          - "Essential To Install:      {{ platform_packages | difference(package_facts.ansible_facts.packages.keys()) | list }}"
          - "Installation Plan Status:  {{ 'READY' if (platform_packages | difference(package_facts.ansible_facts.packages.keys()) | list | length) > 0 else 'ALL INSTALLED' }}"
          - "============================================================================="
      when: 
        - debug_mode | bool
      no_log: true      # Install required packages with retry mechanism and comprehensive error handling
      # Установка необходимых пакетов с механизмом повтора и комплексной обработкой ошибок

    - name: "Execute essential packages installation with retry mechanism and error handling"
      community.general.zypper:
        name: "{{ platform_packages }}"
        state: present
      register: essential_packages_result
      retries: 3
      delay: 10
      until: essential_packages_result is succeeded
      notify: "Restart system services after package installation for SUSE"

    # Log essential packages installation
    # Логирование установки основных пакетов
    - name: "Log essential packages installation"
      ansible.builtin.lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }} | PACKAGE_INSTALL | ESSENTIAL | {{ ansible_hostname }} | {{ 'SUCCESS' if essential_packages_result.changed else 'NO_CHANGE' }} | {{ essential_packages_result.results | selectattr('changed') | map(attribute='item') | list | join(',') if essential_packages_result.results is defined else 'N/A' }}"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: essential_packages_result is defined      # Show detailed installation operation results including success and failure analysis
      # Показать детальные результаты операции установки включая анализ успеха и сбоев


    - name: "Display essential packages installation operation results (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "Essential Packages Installation Operation Results:"
          - "============================================================================="
          - "Packages Changed:          {{ essential_packages_result.changed | default(false) }}"
          - "Packages Installed:        {{ essential_packages_result.results | selectattr('changed') | map(attribute='item') | list if essential_packages_result.results is defined else 'N/A' }}"
          - "Failed Packages:           {{ essential_packages_result.results | selectattr('failed') | map(attribute='item') | list if essential_packages_result.results is defined else 'None' }}"
          - "Operation Status:          {{ 'SUCCESS' if essential_packages_result.changed else 'NO CHANGE' }}"
          - "Installation Completed:    YES"
          - "============================================================================="
      when: 
        - debug_mode | bool
      no_log: true
# Execute optional packages installation with conditional processing and error handling for SUSE/openSUSE
# Выполнение установки дополнительных пакетов с условной обработкой и обработкой ошибок для SUSE/openSUSE
- name: "Execute optional packages installation with conditional processing for SUSE/openSUSE"
  block:      # Install user-defined optional packages with retry mechanism and comprehensive error handling
      # Установка пользовательских дополнительных пакетов с механизмом повтора и комплексной обработкой ошибок

    - name: "Execute user-defined optional packages installation with retry mechanism"
      community.general.zypper:
        name: "{{ platform_optional_packages }}"
        state: present
      register: optional_packages_result
      retries: 3
      delay: 10
      until: optional_packages_result is succeeded
      when: platform_optional_packages | length > 0

    # Log optional packages installation
    # Логирование установки дополнительных пакетов
    - name: "Log optional packages installation"
      ansible.builtin.lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }} | PACKAGE_INSTALL | OPTIONAL | {{ ansible_hostname }} | {{ 'SUCCESS' if optional_packages_result.changed else 'NO_CHANGE' }} | {{ optional_packages_result.results | selectattr('changed') | map(attribute='item') | list | join(',') if optional_packages_result.results is defined else 'N/A' }}"
        create: yes
        mode: '0644'
        owner: root
        group: root
      when: 
        - platform_optional_packages | length > 0
        - optional_packages_result is defined      # Show detailed optional packages installation status and operation analysis
      # Показать детальный статус установки дополнительных пакетов и анализ операции


    - name: "Display optional packages installation operation results (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "Optional Packages Installation Operation Results:"
          - "============================================================================="
          - "Packages Changed:          {{ optional_packages_result.changed | default(false) }}"
          - "Packages Installed:        {{ optional_packages_result.results | selectattr('changed') | map(attribute='item') | list if optional_packages_result.results is defined else 'N/A' }}"
          - "Failed Packages:           {{ optional_packages_result.results | selectattr('failed') | map(attribute='item') | list if optional_packages_result.results is defined else 'None' }}"
          - "Operation Status:          {{ 'SUCCESS' if optional_packages_result.changed else 'NO CHANGE' }}"
          - "Installation Completed:    YES"
          - "============================================================================="
      when: 
        - debug_mode | bool and platform_optional_packages | length > 0
      no_log: true
# Execute comprehensive package installation verification and post-installation validation for SUSE/openSUSE
# Выполнение комплексной проверки установки пакетов и пост-установочной валидации для SUSE/openSUSE
- name: "Execute package installation verification and post-installation validation for SUSE/openSUSE"
  block:      # Collect final package information for comprehensive verification
      # Сбор финальной информации о пакетах для комплексной проверки

    - name: "Gather final comprehensive package information for post-installation verification"
      ansible.builtin.package_facts:
        manager: auto
      register: final_package_facts      # Verify each essential package is present and properly installed
      # Проверка присутствия и корректной установки каждого основного пакета


    - name: "Perform comprehensive verification of all essential packages installation"
      ansible.builtin.assert:
        that:
          - item in final_package_facts.ansible_facts.packages
        fail_msg: "Package '{{ item }}' was not successfully installed"
        success_msg: "Package '{{ item }}' is installed and verified"
      loop: "{{ platform_packages }}"      # Show comprehensive installation results and verification status
      # Показать комплексные результаты установки и статус проверки


    - name: "Display final installation summary and verification results (English)"
      ansible.builtin.debug:
        msg:
          - "============================================================================="
          - "Final Installation Summary and Verification Results:"
          - "============================================================================="
          - "Essential Packages Installed: {{ platform_packages | length }}"
          - "Optional Packages Installed:  {{ platform_optional_packages | length if platform_optional_packages is defined else 0 }}"
          - "Total Packages in System:     {{ final_package_facts.ansible_facts.packages | length }}"
          - "All Essential Verified:       YES"
          - "Verification Status:          SUCCESS"
          - "System Ready for Use:         YES"
          - "============================================================================="
      when: 
        - debug_mode | bool
  rescue:      # Handle any errors that occur during package installation
      # Обработка любых ошибок, возникающих при установке пакетов

    - name: "Handle SUSE/openSUSE package installation errors"
      ansible.builtin.fail:
        msg: "Failed to install packages on SUSE/openSUSE system. Check package availability and system state."
